Description: 'Static Web Site'

Parameters:
  BucketName:
    Type: String
    Description: "Bucket Name"

Resources:
  S3Buckets:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          -
            Action:
                - "s3:GetObject"
            Effect: "Allow"
            Resource:
                Fn::Join:
                  - ""
                  -
                  - "arn:aws:s3:::"
                  -
                  - !Ref BucketName
                  - "/*"
                Principal: "*"
