Description: 'Static Web Site'

Parameters:
  FullDomainName:
    Type: String
    Description: "Full DomainName"
  AcmCertificateArn:
    Type: String
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "arn:aws:acm:.*" 
Resources:
  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: www.huzhi.info.s3.amazonaws.com
          Id: S3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/E229DULKHCO8RO
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - !Ref 'FullDomainName'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref 'AcmCertificateArn'
          SslSupportMethod: sni-only
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn:
    - WebsiteCloudfront
    Properties:
      HostedZoneId: Z3BB8QM0XV5BIY
      Name: !Ref 'FullDomainName'
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteCloudfront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        