Description: 'Static Web Site'

Parameters:
  BucketName:
    Type: String
    Description: "Bucket Name"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2008-10-17"
        Id: "MyFunAssetsBucketPolicy"
        Statement:
          -
            Action:
                - "s3:GetObject"
            Effect: "Allow"
            Resource:
                Fn::Join:
                  - ""
                  -
                  - "arn:aws:s3:::"
                  -
                  - !Ref BucketName
                  - "/*"
                Principal: "*"
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z3BB8QM0XV5BIY
      Name: www.huzhi.info.
      Type: A
      AliasTarget: !GetAtt S3Bucket.DomainName
