Description: 'Static Web Site'

Parameters:
  BucketName:
    Type: String
    Description: "Bucket Name"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Id: MyPolicy
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: "*"
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: BucketName
              - /*
          Sid: ReadAccess
        Version: '2008-10-17'
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z3BB8QM0XV5BIY
      Name: !Ref BucketName
      Type: A
      AliasTarget:
        DNSName: s3-website-ap-southeast-1.amazonaws.com
        HostedZoneId: Z3O0J2DXBE1FTB
