Description: 'Static Web Site'

Parameters:
  BucketName:
    Type: String
    Description: "Bucket Name"

Resources:
  S3Buckets:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
