---
  - name: week1-2
    cloudformation:
      stack_name: "Week-1-2"
      state: present
      region: "ap-southeast-1"
      disable_rollback: true
      template: "cfn-templates/week1-2.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        FullDomainName: "{{full_domain_name}}"
        AcmCertificateArn: "{{acm_certificate_arn}}"
